- name: play 1
  hosts: frontend
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "Play 1 and task 1" 

  - name: play1 and task2
    ansible.builtin.debug:
      msg: "Play 1 and task 2"

- name: play 2
  hosts: frontend
  tasks:
  - name: play2 and task1
    ansible.builtin.debug:
      msg: "Play 2 and task 1" 

  - name: play2 and task2
    ansible.builtin.debug:
      msg: "Play 2 and task 2"
