- name: using conditions in yaml 
  hosts: local
  connection: local
  vars: 
    number: 10
  tasks: 
  - name: using conditions 
    ansible.builtin.debug:
      msg: "Given number {{number}} is not less than 10"
    when: number<10