- name: using loops to install 
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: loops to install 
    ansible.builtin.package:
      name: "{{item}}"
      state: latest 
    loop:
    - nginx
    - mysql
    - zip
    
  - name: start services
    ansible.builtin.service:
      name: "{{item}}"
      state: started
    loop:
    - nginx
    - mysql
  
    