- name: create user and check if already exists
  hosts: local
  connection: local
  become: True
  tasks:
  - name: create system user
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: True
  
  - name: print output
    ansible.builtin.debug:
      msg: "{{ user_output }}"