- name: setup redis db 
  hosts: redis
  become: yes 
  tasks:
  - name: disable module 
    ansible.builtin.command: dnf module disable redis -y

  - name: enable module 7 of redis 
    ansible.builtin.command: dnf module enable redis:7 -y 
  
  - name: install redis 
    ansible.builtin.package:
      name: redis
      state: present 

  - name: to give remote access to db 
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: replace a line in file
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no' 

  - name: start and enable service 
    ansible.builtin.service:
      name: mongod 
      state: restarted 
      enabled: yes 

  