- name: setup rabbitmq
  hosts: rabbitmq
  become: yes 
  tasks:
  - name: install rabbitmq-server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present 

  - name: start and enable service 
    ansible.builtin.service:
      name: rabbitmq
      state: started 
      enabled: yes 