- name: catalogue module
  hosts: catalogue
  become: yes 
  tasks:
  - name: disbale nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs:20
    ansible.builtin.package:
      name: nodejs
      state: present 

  - name: add user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      home: /app 
      shell: /sbin/nologin
      system: yes

  - name: delete directory
    ansible.builtin.file:
      state: absent
      path: /app

  - name: create directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: delete catalogue code
    ansible.builtin.file:
      state: absent
      path: /tmp/catalogue.zip

  - name: download app code to directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes 
  
  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present 

  - name: connnect to mongodb catalogue
    ansible.builtin.command: mongosh mongodb.daws86s-akhil.shop --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  # - name: print the output of catalogue
  #   ansible.builtin.debug:
  #     msg: "{{ catalogue_output }}"

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.daws86s-akhil.shop </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: relaod, enable and start service 
    ansible.builtin.systemd_service:
      name: catalogue
      state: restarted
      daemon_reload: true
      enabled: true
  
