- name: setting up payment module 
  hosts: payment 
  become: yes 
  tasks:
  - name: install python libraries
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc 
    - python3-devel 
    