- name: setting up payment module 
  hosts: payment 
  become: yes 
  tasks:
  - name: install python libraries
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc 
    - python3-devel 
    
  - name: add user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      home: /app 
      shell: /sbin/nologin
      system: yes

  - name: delete directory
    ansible.builtin.file:
      state: absent
      path: /app

  - name: create directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: delete payment code
    ansible.builtin.file:
      state: absent
      path: /tmp/payment.zip

  - name: download app code to directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes 
  
  - name: install libraries
    ansible.builtin.pip:
      requirements: requirements.txt
    args:
      chdir: /app

  - name: copy service file 
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: relaod, enable and start service 
    ansible.builtin.systemd_service:
      name: payment 
      state: restarted
      daemon_reload: true
      enabled: true
  

  