- name: setup frontend 
  hosts: frontend
  become: yes 
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present 

  - name: start and enable service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: delete default data
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: download app code to directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: yes 

  - name: conf file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  
  - name: start and enable service 
    ansible.builtin.service:
      name: nginx
      state: restarted 
